name: transpicturent
description: Pictures at Your Fingertips
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  provider: ^6.0.2
  rxdart: ^0.27.3
  photo_view: ^0.13.0
  url_launcher: ^6.0.18
  gallery_saver: ^2.3.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
